import { describe, expect, test } from "bun:test";

import {
  renderGeneratedConstModule,
  resolveConfigFields,
  type ConfigField,
} from "../codegen/barekey-config-lib";

const fields: Array<ConfigField> = [
  {
    key: "barekeyApiUrl",
    names: ["BAREKEY_API_URL", "VITE_BAREKEY_API_URL"],
  },
];

describe("resolveConfigFields", () => {
  test("prefers the non-prefixed variable name when it exists", async () => {
    const values = await resolveConfigFields(fields, {
      load: async (name) => {
        if (name === "BAREKEY_API_URL") {
          return "https://api.barekey.dev";
        }

        throw new Error("missing");
      },
      isMissingError: (error) => error instanceof Error && error.message === "missing",
    });

    expect(values.barekeyApiUrl).toBe("https://api.barekey.dev");
  });

  test("falls back to the legacy VITE-prefixed name", async () => {
    const values = await resolveConfigFields(fields, {
      load: async (name) => {
        if (name === "BAREKEY_API_URL") {
          throw new Error("missing");
        }
        if (name === "VITE_BAREKEY_API_URL") {
          return "https://api.barekey.dev";
        }

        throw new Error("unexpected");
      },
      isMissingError: (error) => error instanceof Error && error.message === "missing",
    });

    expect(values.barekeyApiUrl).toBe("https://api.barekey.dev");
  });
});

describe("renderGeneratedConstModule", () => {
  test("renders a deterministic generated module", () => {
    const rendered = renderGeneratedConstModule(
      "uiRuntimeConfig",
      {
        barekeyApiUrl: "https://api.barekey.dev",
        clerkPublishableKey: "pk_test_123",
      },
      "@barekey/sdk config sync",
    );

    expect(rendered).toContain("This file is generated by @barekey/sdk config sync.");
    expect(rendered).toContain("export const uiRuntimeConfig = {");
    expect(rendered).toContain("\"barekeyApiUrl\": \"https://api.barekey.dev\"");
    expect(rendered).toContain("\"clerkPublishableKey\": \"pk_test_123\"");
  });
});
