import { writeFile } from "node:fs/promises";

export type TypegenManifest = {
  orgId: string;
  orgSlug: string;
  projectSlug: string;
  stageSlug: string;
  generatedAtMs: number;
  manifestVersion: string;
  variables: Array<{
    name: string;
    kind: "secret" | "ab_roll" | "rollout";
    declaredType: "string" | "number" | "boolean" | "json";
    required: boolean;
    updatedAtMs: number;
  }>;
};

function toTypeForVariable(input: TypegenManifest["variables"][number]): string {
  if (input.declaredType === "number") {
    return "number";
  }
  if (input.declaredType === "boolean") {
    return "boolean";
  }
  if (input.declaredType === "json") {
    return "unknown";
  }
  return "string";
}

export async function writeTypegenFile(input: {
  manifest: TypegenManifest;
  outPath: string;
}): Promise<void> {
  const keys = input.manifest.variables
    .map((row) => row.name)
    .sort((left, right) => left.localeCompare(right));

  const unionLines = keys.map((key) => `  | ${JSON.stringify(key)}`).join("\n");
  const mapLines = input.manifest.variables
    .slice()
    .sort((left, right) => left.name.localeCompare(right.name))
    .map((row) => `  ${JSON.stringify(row.name)}: ${toTypeForVariable(row)};`)
    .join("\n");

  const contents = `/* eslint-disable */\n/* This file is generated by barekey typegen. */\n\nexport type BarekeyKnownKey =\n${unionLines.length > 0 ? unionLines : "  never"};\n\nexport interface BarekeyTypeMap {\n${mapLines}\n}\n\nexport const barekeyManifestVersion = ${JSON.stringify(input.manifest.manifestVersion)};\n`;

  await writeFile(input.outPath, contents, "utf8");
}
