import { writeFile } from "node:fs/promises";

export type TypegenManifest = {
  orgId: string;
  orgSlug: string;
  projectSlug: string;
  stageSlug: string;
  generatedAtMs: number;
  manifestVersion: string;
  variables: Array<{
    name: string;
    kind: "secret" | "ab_roll" | "rollout";
    declaredType: "string" | "boolean" | "int64" | "float" | "date" | "json";
    required: boolean;
    updatedAtMs: number;
    typeScriptType: string;
  }>;
};

export async function writeTypegenFile(input: {
  manifest: TypegenManifest;
  outPath: string;
}): Promise<void> {
  const keys = input.manifest.variables
    .map((row) => row.name)
    .sort((left, right) => left.localeCompare(right));

  const unionLines = keys.map((key) => `  | ${JSON.stringify(key)}`).join("\n");
  const mapLines = input.manifest.variables
    .slice()
    .sort((left, right) => left.name.localeCompare(right.name))
    .map((row) => `    ${JSON.stringify(row.name)}: ${row.typeScriptType};`)
    .join("\n");

  const contents = `/* eslint-disable */\n/* This file is generated by barekey typegen. */\n\nimport type { BarekeyTemporalInstant } from "@barekey/sdk";\nimport "@barekey/sdk";\n\ndeclare module "@barekey/sdk" {\n  interface BarekeyGeneratedTypeMap {\n${mapLines}\n  }\n}\n\nexport type BarekeyKnownKey =\n${unionLines.length > 0 ? unionLines : "  never"};\n\nexport const barekeyManifestVersion = ${JSON.stringify(input.manifest.manifestVersion)};\n`;

  await writeFile(input.outPath, contents, "utf8");
}
