export type ConfigField = {
  key: string;
  names: Array<string>;
};

export function renderGeneratedConstModule(
  exportName: string,
  values: Record<string, string>,
  sourceLabel: string,
): string {
  return `/* eslint-disable */
/* This file is generated by ${sourceLabel}. */

export const ${exportName} = ${JSON.stringify(values, null, 2)} as const;
`;
}

export async function resolveConfigFields(
  fields: Array<ConfigField>,
  input: {
    load: (name: string) => Promise<string>;
    isMissingError: (error: unknown) => boolean;
  },
): Promise<Record<string, string>> {
  const values: Record<string, string> = {};

  for (const field of fields) {
    values[field.key] = await resolveFieldValue(field, input);
  }

  return values;
}

async function resolveFieldValue(
  field: ConfigField,
  input: {
    load: (name: string) => Promise<string>;
    isMissingError: (error: unknown) => boolean;
  },
): Promise<string> {
  for (const name of field.names) {
    try {
      const value = (await input.load(name)).trim();
      if (value.length === 0) {
        throw new Error(`Barekey variable ${name} is empty.`);
      }
      return value;
    } catch (error: unknown) {
      if (input.isMissingError(error)) {
        continue;
      }

      throw new Error(`Failed to resolve Barekey variable ${name}.`, {
        cause: error,
      });
    }
  }

  throw new Error(
    `Missing Barekey config value for ${field.key}. Tried ${field.names.join(", ")}.`,
  );
}
