/* eslint-disable */
/**
 * Generated `api` utility.
 *
 * THIS CODE IS AUTOMATICALLY GENERATED.
 *
 * To regenerate, run `npx convex dev`.
 * @module
 */

import type * as audit from "../audit.js";
import type * as audit_append from "../audit/append.js";
import type * as audit_clerk_webhooks from "../audit/clerk_webhooks.js";
import type * as audit_list from "../audit/list.js";
import type * as audit_list_current_org from "../audit/list/current_org.js";
import type * as audit_list_preview from "../audit/list/preview.js";
import type * as audit_list_project from "../audit/list/project.js";
import type * as audit_list_shared from "../audit/list/shared.js";
import type * as audit_normalization from "../audit/normalization.js";
import type * as audit_prune from "../audit/prune.js";
import type * as audit_record_insert from "../audit/record_insert.js";
import type * as audit_refs from "../audit/refs.js";
import type * as audit_types from "../audit/types.js";
import type * as autumn from "../autumn.js";
import type * as bootstrap from "../bootstrap.js";
import type * as clerk from "../clerk.js";
import type * as cli_auth from "../cli_auth.js";
import type * as cli_auth_device_code_complete from "../cli_auth/device_code_complete.js";
import type * as cli_auth_device_code_create from "../cli_auth/device_code_create.js";
import type * as cli_auth_device_code_poll from "../cli_auth/device_code_poll.js";
import type * as cli_auth_sessions from "../cli_auth/sessions.js";
import type * as cli_auth_sessions_authenticate from "../cli_auth/sessions/authenticate.js";
import type * as cli_auth_sessions_refresh from "../cli_auth/sessions/refresh.js";
import type * as cli_auth_sessions_revoke from "../cli_auth/sessions/revoke.js";
import type * as cli_auth_sessions_shared from "../cli_auth/sessions/shared.js";
import type * as cli_auth_token_helpers from "../cli_auth/token_helpers.js";
import type * as confect from "../confect.js";
import type * as crons from "../crons.js";
import type * as cutover from "../cutover.js";
import type * as http from "../http.js";
import type * as lib_audit from "../lib/audit.js";
import type * as lib_auth from "../lib/auth.js";
import type * as lib_auth_expected_org from "../lib/auth/expected_org.js";
import type * as lib_auth_identity from "../lib/auth/identity.js";
import type * as lib_auth_org_claims from "../lib/auth/org_claims.js";
import type * as lib_auth_shared from "../lib/auth/shared.js";
import type * as lib_auth_types from "../lib/auth/types.js";
import type * as lib_confect_audit from "../lib/confect/audit.js";
import type * as lib_confect_billing from "../lib/confect/billing.js";
import type * as lib_confect_boundary from "../lib/confect/boundary.js";
import type * as lib_confect_effect from "../lib/confect/effect.js";
import type * as lib_confect_http from "../lib/confect/http.js";
import type * as lib_confect_project_scope from "../lib/confect/project/scope.js";
import type * as lib_confect_runtime_audit from "../lib/confect/runtime/audit.js";
import type * as lib_confect_runtime_billing from "../lib/confect/runtime/billing.js";
import type * as lib_confect_runtime_context from "../lib/confect/runtime/context.js";
import type * as lib_confect_runtime_errors from "../lib/confect/runtime/errors.js";
import type * as lib_confect_runtime_layer from "../lib/confect/runtime/layer.js";
import type * as lib_confect_runtime_project_scope from "../lib/confect/runtime/project_scope.js";
import type * as lib_confect_schema_common from "../lib/confect/schema/common.js";
import type * as lib_confect_schema_tables_audit from "../lib/confect/schema/tables/audit.js";
import type * as lib_confect_schema_tables_billing from "../lib/confect/schema/tables/billing.js";
import type * as lib_confect_schema_tables_cli from "../lib/confect/schema/tables/cli.js";
import type * as lib_confect_schema_tables_projects from "../lib/confect/schema/tables/projects.js";
import type * as lib_confect_schema_tables_users from "../lib/confect/schema/tables/users.js";
import type * as lib_confect_services from "../lib/confect/services.js";
import type * as lib_confect_validators from "../lib/confect/validators.js";
import type * as lib_declared_types from "../lib/declared/types.js";
import type * as lib_encryption from "../lib/encryption.js";
import type * as lib_encryption_base64 from "../lib/encryption/base64.js";
import type * as lib_encryption_cipher from "../lib/encryption/cipher.js";
import type * as lib_encryption_constants from "../lib/encryption/constants.js";
import type * as lib_encryption_envelope from "../lib/encryption/envelope.js";
import type * as lib_encryption_keys from "../lib/encryption/keys.js";
import type * as lib_encryption_project from "../lib/encryption/project.js";
import type * as lib_errors_effect from "../lib/errors/effect.js";
import type * as lib_http_auth from "../lib/http/auth.js";
import type * as lib_http_cli_device_complete from "../lib/http/cli/device_complete.js";
import type * as lib_http_cli_device_poll from "../lib/http/cli/device_poll.js";
import type * as lib_http_cli_device_start from "../lib/http/cli/device_start.js";
import type * as lib_http_cli_index from "../lib/http/cli/index.js";
import type * as lib_http_cli_logout from "../lib/http/cli/logout.js";
import type * as lib_http_cli_session from "../lib/http/cli/session.js";
import type * as lib_http_cli_shared from "../lib/http/cli/shared.js";
import type * as lib_http_cli_token_refresh from "../lib/http/cli/token_refresh.js";
import type * as lib_http_env_errors from "../lib/http/env/errors.js";
import type * as lib_http_env_index from "../lib/http/env/index.js";
import type * as lib_http_env_parsing from "../lib/http/env/parsing.js";
import type * as lib_http_env_parsing_definitions from "../lib/http/env/parsing/definitions.js";
import type * as lib_http_env_parsing_evaluate from "../lib/http/env/parsing/evaluate.js";
import type * as lib_http_env_parsing_list from "../lib/http/env/parsing/list.js";
import type * as lib_http_env_parsing_shared from "../lib/http/env/parsing/shared.js";
import type * as lib_http_env_parsing_write from "../lib/http/env/parsing/write.js";
import type * as lib_http_env_routes_definitions from "../lib/http/env/routes/definitions.js";
import type * as lib_http_env_routes_evaluate_batch from "../lib/http/env/routes/evaluate_batch.js";
import type * as lib_http_env_routes_evaluate_one from "../lib/http/env/routes/evaluate_one.js";
import type * as lib_http_env_routes_index from "../lib/http/env/routes/index.js";
import type * as lib_http_env_routes_list from "../lib/http/env/routes/list.js";
import type * as lib_http_env_routes_public_definitions from "../lib/http/env/routes/public_definitions.js";
import type * as lib_http_env_routes_pull from "../lib/http/env/routes/pull.js";
import type * as lib_http_env_routes_shared from "../lib/http/env/routes/shared.js";
import type * as lib_http_env_routes_write from "../lib/http/env/routes/write.js";
import type * as lib_http_env_types from "../lib/http/env/types.js";
import type * as lib_http_env_values from "../lib/http/env/values.js";
import type * as lib_http_misc from "../lib/http/misc.js";
import type * as lib_http_responses from "../lib/http/responses.js";
import type * as lib_payments_catalog from "../lib/payments/catalog.js";
import type * as lib_payments_management_billing_portal from "../lib/payments/management/billing_portal.js";
import type * as lib_payments_management_change_plan from "../lib/payments/management/change_plan.js";
import type * as lib_payments_management_change_plan_audit from "../lib/payments/management/change_plan/audit.js";
import type * as lib_payments_management_change_plan_free_credit from "../lib/payments/management/change_plan/free_credit.js";
import type * as lib_payments_management_change_plan_handler from "../lib/payments/management/change_plan/handler.js";
import type * as lib_payments_management_change_plan_post_attach from "../lib/payments/management/change_plan/post_attach.js";
import type * as lib_payments_management_change_plan_shared from "../lib/payments/management/change_plan/shared.js";
import type * as lib_payments_management_free_credit from "../lib/payments/management/free_credit.js";
import type * as lib_payments_management_index from "../lib/payments/management/index.js";
import type * as lib_payments_state from "../lib/payments/state.js";
import type * as lib_payments_variants from "../lib/payments/variants.js";
import type * as lib_payments_variants_client from "../lib/payments/variants/client.js";
import type * as lib_payments_variants_pricing from "../lib/payments/variants/pricing.js";
import type * as lib_payments_variants_shared from "../lib/payments/variants/shared.js";
import type * as lib_payments_variants_workspace_plan from "../lib/payments/variants/workspace_plan.js";
import type * as lib_project_variables_contracts from "../lib/project_variables/contracts.js";
import type * as lib_project_variables_rows from "../lib/project_variables/rows.js";
import type * as lib_project_variables_schedules from "../lib/project_variables/schedules.js";
import type * as lib_project_variables_validation from "../lib/project_variables/validation.js";
import type * as lib_projects_scope_errors from "../lib/projects/scope/errors.js";
import type * as lib_projects_scope_index from "../lib/projects/scope/index.js";
import type * as lib_projects_scope_programs from "../lib/projects/scope/programs.js";
import type * as lib_projects_scope_readers from "../lib/projects/scope/readers.js";
import type * as lib_rollout from "../lib/rollout.js";
import type * as lib_runtime_config_index from "../lib/runtime/config/index.js";
import type * as lib_runtime_config_loader from "../lib/runtime/config/loader.js";
import type * as lib_timezone from "../lib/timezone.js";
import type * as lib_visibility from "../lib/visibility.js";
import type * as orgs from "../orgs.js";
import type * as payments from "../payments.js";
import type * as payments_billing_state from "../payments/billing_state.js";
import type * as payments_catalog from "../payments/catalog.js";
import type * as payments_credit_grants from "../payments/credit_grants.js";
import type * as payments_credit_grants_consume from "../payments/credit_grants/consume.js";
import type * as payments_credit_grants_ensure from "../payments/credit_grants/ensure.js";
import type * as payments_credit_grants_rows from "../payments/credit_grants/rows.js";
import type * as payments_credit_grants_shared from "../payments/credit_grants/shared.js";
import type * as payments_credit_queries from "../payments/credit_queries.js";
import type * as payments_credit_revocations from "../payments/credit_revocations.js";
import type * as payments_credit_revocations_revoke_by_org from "../payments/credit_revocations/revoke_by_org.js";
import type * as payments_credit_revocations_revoke_current from "../payments/credit_revocations/revoke_current.js";
import type * as payments_credit_revocations_rows from "../payments/credit_revocations/rows.js";
import type * as payments_credit_revocations_shared from "../payments/credit_revocations/shared.js";
import type * as payments_helpers from "../payments/helpers.js";
import type * as payments_management_actions from "../payments/management_actions.js";
import type * as payments_metered_usage from "../payments/metered_usage.js";
import type * as payments_metered_usage_compensate_current from "../payments/metered_usage/compensate_current.js";
import type * as payments_metered_usage_compensate_org from "../payments/metered_usage/compensate_org.js";
import type * as payments_metered_usage_reserve_current from "../payments/metered_usage/reserve_current.js";
import type * as payments_metered_usage_reserve_org from "../payments/metered_usage/reserve_org.js";
import type * as payments_metered_usage_shared from "../payments/metered_usage/shared.js";
import type * as payments_refs from "../payments/refs.js";
import type * as payments_request_log from "../payments/request_log.js";
import type * as payments_storage from "../payments/storage.js";
import type * as payments_storage_apply_delta from "../payments/storage/apply_delta.js";
import type * as payments_storage_ensure_usage from "../payments/storage/ensure_usage.js";
import type * as payments_storage_get_usage from "../payments/storage/get_usage.js";
import type * as payments_storage_shared from "../payments/storage/shared.js";
import type * as payments_storage_upsert_snapshot from "../payments/storage/upsert_snapshot.js";
import type * as payments_types from "../payments/types.js";
import type * as payments_workspace_plan from "../payments/workspace_plan.js";
import type * as payments_workspace_plan_assert_current from "../payments/workspace_plan/assert_current.js";
import type * as payments_workspace_plan_assert_org from "../payments/workspace_plan/assert_org.js";
import type * as payments_workspace_plan_shared from "../payments/workspace_plan/shared.js";
import type * as payments_workspace_plan_status from "../payments/workspace_plan/status.js";
import type * as project_stages from "../project_stages.js";
import type * as project_stages_access from "../project_stages/access.js";
import type * as project_stages_create from "../project_stages/create.js";
import type * as project_stages_defaults from "../project_stages/defaults.js";
import type * as project_stages_delete from "../project_stages/delete.js";
import type * as project_stages_errors from "../project_stages/errors.js";
import type * as project_stages_queries from "../project_stages/queries.js";
import type * as project_stages_rename from "../project_stages/rename.js";
import type * as project_stages_slug from "../project_stages/slug.js";
import type * as project_stages_types from "../project_stages/types.js";
import type * as project_stages_validation from "../project_stages/validation.js";
import type * as project_variable_schedules from "../project_variable_schedules.js";
import type * as project_variable_schedules_access from "../project_variable_schedules/access.js";
import type * as project_variable_schedules_cancel from "../project_variable_schedules/cancel.js";
import type * as project_variable_schedules_create from "../project_variable_schedules/create.js";
import type * as project_variable_schedules_decrypt from "../project_variable_schedules/decrypt.js";
import type * as project_variable_schedules_errors from "../project_variable_schedules/errors.js";
import type * as project_variable_schedules_execution from "../project_variable_schedules/execution.js";
import type * as project_variable_schedules_execution_load from "../project_variable_schedules/execution/load.js";
import type * as project_variable_schedules_execution_run from "../project_variable_schedules/execution/run.js";
import type * as project_variable_schedules_execution_status from "../project_variable_schedules/execution/status.js";
import type * as project_variable_schedules_execution_types from "../project_variable_schedules/execution/types.js";
import type * as project_variable_schedules_list from "../project_variable_schedules/list.js";
import type * as project_variable_schedules_refs from "../project_variable_schedules/refs.js";
import type * as project_variable_schedules_snapshot from "../project_variable_schedules/snapshot.js";
import type * as project_variable_schedules_snapshot_attach from "../project_variable_schedules/snapshot/attach.js";
import type * as project_variable_schedules_snapshot_errors from "../project_variable_schedules/snapshot/errors.js";
import type * as project_variable_schedules_snapshot_prepare from "../project_variable_schedules/snapshot/prepare.js";
import type * as project_variable_schedules_summary from "../project_variable_schedules/summary.js";
import type * as project_variable_schedules_types from "../project_variable_schedules/types.js";
import type * as project_variable_schedules_update from "../project_variable_schedules/update.js";
import type * as project_variable_schedules_validators from "../project_variable_schedules/validators.js";
import type * as project_variables from "../project_variables.js";
import type * as project_variables_access from "../project_variables/access.js";
import type * as project_variables_apply_prepared_variable_writes from "../project_variables/apply_prepared_variable_writes.js";
import type * as project_variables_decrypt from "../project_variables/decrypt.js";
import type * as project_variables_decrypt_current_org_stage from "../project_variables/decrypt/current_org_stage.js";
import type * as project_variables_decrypt_org_stage from "../project_variables/decrypt/org_stage.js";
import type * as project_variables_decrypt_stage from "../project_variables/decrypt/stage.js";
import type * as project_variables_draft_apply from "../project_variables/draft/apply.js";
import type * as project_variables_draft_prepare from "../project_variables/draft/prepare.js";
import type * as project_variables_draft_actions from "../project_variables/draft_actions.js";
import type * as project_variables_draft_mutations from "../project_variables/draft_mutations.js";
import type * as project_variables_errors from "../project_variables/errors.js";
import type * as project_variables_prepare_variable_writes from "../project_variables/prepare_variable_writes.js";
import type * as project_variables_prepared_write_actions from "../project_variables/prepared_write_actions.js";
import type * as project_variables_prepared_write_actions_apply from "../project_variables/prepared_write_actions/apply.js";
import type * as project_variables_prepared_write_actions_write from "../project_variables/prepared_write_actions/write.js";
import type * as project_variables_prepared_write_mutations from "../project_variables/prepared_write_mutations.js";
import type * as project_variables_prepared_write_summary from "../project_variables/prepared_write_summary.js";
import type * as project_variables_queries from "../project_variables/queries.js";
import type * as project_variables_query_list_current_org_stage from "../project_variables/query/list_current_org_stage.js";
import type * as project_variables_query_list_metadata from "../project_variables/query/list_metadata.js";
import type * as project_variables_query_resolve_public_rows from "../project_variables/query/resolve_public_rows.js";
import type * as project_variables_query_resolve_rows from "../project_variables/query/resolve_rows.js";
import type * as project_variables_query_shared from "../project_variables/query/shared.js";
import type * as project_variables_refs from "../project_variables/refs.js";
import type * as project_variables_types from "../project_variables/types.js";
import type * as project_variables_writes_prepare from "../project_variables/writes/prepare.js";
import type * as project_variables_writes_secret from "../project_variables/writes/secret.js";
import type * as project_variables_writes_variants from "../project_variables/writes/variants.js";
import type * as projects from "../projects.js";
import type * as projects_create from "../projects/create.js";
import type * as projects_delete from "../projects/delete.js";
import type * as projects_queries from "../projects/queries.js";
import type * as projects_slug from "../projects/slug.js";
import type * as projects_types from "../projects/types.js";
import type * as typegen from "../typegen.js";
import type * as user_preferences from "../user_preferences.js";
import type * as users from "../users.js";
import type * as users_ensure from "../users/ensure.js";
import type * as users_queries from "../users/queries.js";
import type * as users_shared from "../users/shared.js";

import type {
  ApiFromModules,
  FilterApi,
  FunctionReference,
} from "convex/server";

declare const fullApi: ApiFromModules<{
  audit: typeof audit;
  "audit/append": typeof audit_append;
  "audit/clerk_webhooks": typeof audit_clerk_webhooks;
  "audit/list": typeof audit_list;
  "audit/list/current_org": typeof audit_list_current_org;
  "audit/list/preview": typeof audit_list_preview;
  "audit/list/project": typeof audit_list_project;
  "audit/list/shared": typeof audit_list_shared;
  "audit/normalization": typeof audit_normalization;
  "audit/prune": typeof audit_prune;
  "audit/record_insert": typeof audit_record_insert;
  "audit/refs": typeof audit_refs;
  "audit/types": typeof audit_types;
  autumn: typeof autumn;
  bootstrap: typeof bootstrap;
  clerk: typeof clerk;
  cli_auth: typeof cli_auth;
  "cli_auth/device_code_complete": typeof cli_auth_device_code_complete;
  "cli_auth/device_code_create": typeof cli_auth_device_code_create;
  "cli_auth/device_code_poll": typeof cli_auth_device_code_poll;
  "cli_auth/sessions": typeof cli_auth_sessions;
  "cli_auth/sessions/authenticate": typeof cli_auth_sessions_authenticate;
  "cli_auth/sessions/refresh": typeof cli_auth_sessions_refresh;
  "cli_auth/sessions/revoke": typeof cli_auth_sessions_revoke;
  "cli_auth/sessions/shared": typeof cli_auth_sessions_shared;
  "cli_auth/token_helpers": typeof cli_auth_token_helpers;
  confect: typeof confect;
  crons: typeof crons;
  cutover: typeof cutover;
  http: typeof http;
  "lib/audit": typeof lib_audit;
  "lib/auth": typeof lib_auth;
  "lib/auth/expected_org": typeof lib_auth_expected_org;
  "lib/auth/identity": typeof lib_auth_identity;
  "lib/auth/org_claims": typeof lib_auth_org_claims;
  "lib/auth/shared": typeof lib_auth_shared;
  "lib/auth/types": typeof lib_auth_types;
  "lib/confect/audit": typeof lib_confect_audit;
  "lib/confect/billing": typeof lib_confect_billing;
  "lib/confect/boundary": typeof lib_confect_boundary;
  "lib/confect/effect": typeof lib_confect_effect;
  "lib/confect/http": typeof lib_confect_http;
  "lib/confect/project/scope": typeof lib_confect_project_scope;
  "lib/confect/runtime/audit": typeof lib_confect_runtime_audit;
  "lib/confect/runtime/billing": typeof lib_confect_runtime_billing;
  "lib/confect/runtime/context": typeof lib_confect_runtime_context;
  "lib/confect/runtime/errors": typeof lib_confect_runtime_errors;
  "lib/confect/runtime/layer": typeof lib_confect_runtime_layer;
  "lib/confect/runtime/project_scope": typeof lib_confect_runtime_project_scope;
  "lib/confect/schema/common": typeof lib_confect_schema_common;
  "lib/confect/schema/tables/audit": typeof lib_confect_schema_tables_audit;
  "lib/confect/schema/tables/billing": typeof lib_confect_schema_tables_billing;
  "lib/confect/schema/tables/cli": typeof lib_confect_schema_tables_cli;
  "lib/confect/schema/tables/projects": typeof lib_confect_schema_tables_projects;
  "lib/confect/schema/tables/users": typeof lib_confect_schema_tables_users;
  "lib/confect/services": typeof lib_confect_services;
  "lib/confect/validators": typeof lib_confect_validators;
  "lib/declared/types": typeof lib_declared_types;
  "lib/encryption": typeof lib_encryption;
  "lib/encryption/base64": typeof lib_encryption_base64;
  "lib/encryption/cipher": typeof lib_encryption_cipher;
  "lib/encryption/constants": typeof lib_encryption_constants;
  "lib/encryption/envelope": typeof lib_encryption_envelope;
  "lib/encryption/keys": typeof lib_encryption_keys;
  "lib/encryption/project": typeof lib_encryption_project;
  "lib/errors/effect": typeof lib_errors_effect;
  "lib/http/auth": typeof lib_http_auth;
  "lib/http/cli/device_complete": typeof lib_http_cli_device_complete;
  "lib/http/cli/device_poll": typeof lib_http_cli_device_poll;
  "lib/http/cli/device_start": typeof lib_http_cli_device_start;
  "lib/http/cli/index": typeof lib_http_cli_index;
  "lib/http/cli/logout": typeof lib_http_cli_logout;
  "lib/http/cli/session": typeof lib_http_cli_session;
  "lib/http/cli/shared": typeof lib_http_cli_shared;
  "lib/http/cli/token_refresh": typeof lib_http_cli_token_refresh;
  "lib/http/env/errors": typeof lib_http_env_errors;
  "lib/http/env/index": typeof lib_http_env_index;
  "lib/http/env/parsing": typeof lib_http_env_parsing;
  "lib/http/env/parsing/definitions": typeof lib_http_env_parsing_definitions;
  "lib/http/env/parsing/evaluate": typeof lib_http_env_parsing_evaluate;
  "lib/http/env/parsing/list": typeof lib_http_env_parsing_list;
  "lib/http/env/parsing/shared": typeof lib_http_env_parsing_shared;
  "lib/http/env/parsing/write": typeof lib_http_env_parsing_write;
  "lib/http/env/routes/definitions": typeof lib_http_env_routes_definitions;
  "lib/http/env/routes/evaluate_batch": typeof lib_http_env_routes_evaluate_batch;
  "lib/http/env/routes/evaluate_one": typeof lib_http_env_routes_evaluate_one;
  "lib/http/env/routes/index": typeof lib_http_env_routes_index;
  "lib/http/env/routes/list": typeof lib_http_env_routes_list;
  "lib/http/env/routes/public_definitions": typeof lib_http_env_routes_public_definitions;
  "lib/http/env/routes/pull": typeof lib_http_env_routes_pull;
  "lib/http/env/routes/shared": typeof lib_http_env_routes_shared;
  "lib/http/env/routes/write": typeof lib_http_env_routes_write;
  "lib/http/env/types": typeof lib_http_env_types;
  "lib/http/env/values": typeof lib_http_env_values;
  "lib/http/misc": typeof lib_http_misc;
  "lib/http/responses": typeof lib_http_responses;
  "lib/payments/catalog": typeof lib_payments_catalog;
  "lib/payments/management/billing_portal": typeof lib_payments_management_billing_portal;
  "lib/payments/management/change_plan": typeof lib_payments_management_change_plan;
  "lib/payments/management/change_plan/audit": typeof lib_payments_management_change_plan_audit;
  "lib/payments/management/change_plan/free_credit": typeof lib_payments_management_change_plan_free_credit;
  "lib/payments/management/change_plan/handler": typeof lib_payments_management_change_plan_handler;
  "lib/payments/management/change_plan/post_attach": typeof lib_payments_management_change_plan_post_attach;
  "lib/payments/management/change_plan/shared": typeof lib_payments_management_change_plan_shared;
  "lib/payments/management/free_credit": typeof lib_payments_management_free_credit;
  "lib/payments/management/index": typeof lib_payments_management_index;
  "lib/payments/state": typeof lib_payments_state;
  "lib/payments/variants": typeof lib_payments_variants;
  "lib/payments/variants/client": typeof lib_payments_variants_client;
  "lib/payments/variants/pricing": typeof lib_payments_variants_pricing;
  "lib/payments/variants/shared": typeof lib_payments_variants_shared;
  "lib/payments/variants/workspace_plan": typeof lib_payments_variants_workspace_plan;
  "lib/project_variables/contracts": typeof lib_project_variables_contracts;
  "lib/project_variables/rows": typeof lib_project_variables_rows;
  "lib/project_variables/schedules": typeof lib_project_variables_schedules;
  "lib/project_variables/validation": typeof lib_project_variables_validation;
  "lib/projects/scope/errors": typeof lib_projects_scope_errors;
  "lib/projects/scope/index": typeof lib_projects_scope_index;
  "lib/projects/scope/programs": typeof lib_projects_scope_programs;
  "lib/projects/scope/readers": typeof lib_projects_scope_readers;
  "lib/rollout": typeof lib_rollout;
  "lib/runtime/config/index": typeof lib_runtime_config_index;
  "lib/runtime/config/loader": typeof lib_runtime_config_loader;
  "lib/timezone": typeof lib_timezone;
  "lib/visibility": typeof lib_visibility;
  orgs: typeof orgs;
  payments: typeof payments;
  "payments/billing_state": typeof payments_billing_state;
  "payments/catalog": typeof payments_catalog;
  "payments/credit_grants": typeof payments_credit_grants;
  "payments/credit_grants/consume": typeof payments_credit_grants_consume;
  "payments/credit_grants/ensure": typeof payments_credit_grants_ensure;
  "payments/credit_grants/rows": typeof payments_credit_grants_rows;
  "payments/credit_grants/shared": typeof payments_credit_grants_shared;
  "payments/credit_queries": typeof payments_credit_queries;
  "payments/credit_revocations": typeof payments_credit_revocations;
  "payments/credit_revocations/revoke_by_org": typeof payments_credit_revocations_revoke_by_org;
  "payments/credit_revocations/revoke_current": typeof payments_credit_revocations_revoke_current;
  "payments/credit_revocations/rows": typeof payments_credit_revocations_rows;
  "payments/credit_revocations/shared": typeof payments_credit_revocations_shared;
  "payments/helpers": typeof payments_helpers;
  "payments/management_actions": typeof payments_management_actions;
  "payments/metered_usage": typeof payments_metered_usage;
  "payments/metered_usage/compensate_current": typeof payments_metered_usage_compensate_current;
  "payments/metered_usage/compensate_org": typeof payments_metered_usage_compensate_org;
  "payments/metered_usage/reserve_current": typeof payments_metered_usage_reserve_current;
  "payments/metered_usage/reserve_org": typeof payments_metered_usage_reserve_org;
  "payments/metered_usage/shared": typeof payments_metered_usage_shared;
  "payments/refs": typeof payments_refs;
  "payments/request_log": typeof payments_request_log;
  "payments/storage": typeof payments_storage;
  "payments/storage/apply_delta": typeof payments_storage_apply_delta;
  "payments/storage/ensure_usage": typeof payments_storage_ensure_usage;
  "payments/storage/get_usage": typeof payments_storage_get_usage;
  "payments/storage/shared": typeof payments_storage_shared;
  "payments/storage/upsert_snapshot": typeof payments_storage_upsert_snapshot;
  "payments/types": typeof payments_types;
  "payments/workspace_plan": typeof payments_workspace_plan;
  "payments/workspace_plan/assert_current": typeof payments_workspace_plan_assert_current;
  "payments/workspace_plan/assert_org": typeof payments_workspace_plan_assert_org;
  "payments/workspace_plan/shared": typeof payments_workspace_plan_shared;
  "payments/workspace_plan/status": typeof payments_workspace_plan_status;
  project_stages: typeof project_stages;
  "project_stages/access": typeof project_stages_access;
  "project_stages/create": typeof project_stages_create;
  "project_stages/defaults": typeof project_stages_defaults;
  "project_stages/delete": typeof project_stages_delete;
  "project_stages/errors": typeof project_stages_errors;
  "project_stages/queries": typeof project_stages_queries;
  "project_stages/rename": typeof project_stages_rename;
  "project_stages/slug": typeof project_stages_slug;
  "project_stages/types": typeof project_stages_types;
  "project_stages/validation": typeof project_stages_validation;
  project_variable_schedules: typeof project_variable_schedules;
  "project_variable_schedules/access": typeof project_variable_schedules_access;
  "project_variable_schedules/cancel": typeof project_variable_schedules_cancel;
  "project_variable_schedules/create": typeof project_variable_schedules_create;
  "project_variable_schedules/decrypt": typeof project_variable_schedules_decrypt;
  "project_variable_schedules/errors": typeof project_variable_schedules_errors;
  "project_variable_schedules/execution": typeof project_variable_schedules_execution;
  "project_variable_schedules/execution/load": typeof project_variable_schedules_execution_load;
  "project_variable_schedules/execution/run": typeof project_variable_schedules_execution_run;
  "project_variable_schedules/execution/status": typeof project_variable_schedules_execution_status;
  "project_variable_schedules/execution/types": typeof project_variable_schedules_execution_types;
  "project_variable_schedules/list": typeof project_variable_schedules_list;
  "project_variable_schedules/refs": typeof project_variable_schedules_refs;
  "project_variable_schedules/snapshot": typeof project_variable_schedules_snapshot;
  "project_variable_schedules/snapshot/attach": typeof project_variable_schedules_snapshot_attach;
  "project_variable_schedules/snapshot/errors": typeof project_variable_schedules_snapshot_errors;
  "project_variable_schedules/snapshot/prepare": typeof project_variable_schedules_snapshot_prepare;
  "project_variable_schedules/summary": typeof project_variable_schedules_summary;
  "project_variable_schedules/types": typeof project_variable_schedules_types;
  "project_variable_schedules/update": typeof project_variable_schedules_update;
  "project_variable_schedules/validators": typeof project_variable_schedules_validators;
  project_variables: typeof project_variables;
  "project_variables/access": typeof project_variables_access;
  "project_variables/apply_prepared_variable_writes": typeof project_variables_apply_prepared_variable_writes;
  "project_variables/decrypt": typeof project_variables_decrypt;
  "project_variables/decrypt/current_org_stage": typeof project_variables_decrypt_current_org_stage;
  "project_variables/decrypt/org_stage": typeof project_variables_decrypt_org_stage;
  "project_variables/decrypt/stage": typeof project_variables_decrypt_stage;
  "project_variables/draft/apply": typeof project_variables_draft_apply;
  "project_variables/draft/prepare": typeof project_variables_draft_prepare;
  "project_variables/draft_actions": typeof project_variables_draft_actions;
  "project_variables/draft_mutations": typeof project_variables_draft_mutations;
  "project_variables/errors": typeof project_variables_errors;
  "project_variables/prepare_variable_writes": typeof project_variables_prepare_variable_writes;
  "project_variables/prepared_write_actions": typeof project_variables_prepared_write_actions;
  "project_variables/prepared_write_actions/apply": typeof project_variables_prepared_write_actions_apply;
  "project_variables/prepared_write_actions/write": typeof project_variables_prepared_write_actions_write;
  "project_variables/prepared_write_mutations": typeof project_variables_prepared_write_mutations;
  "project_variables/prepared_write_summary": typeof project_variables_prepared_write_summary;
  "project_variables/queries": typeof project_variables_queries;
  "project_variables/query/list_current_org_stage": typeof project_variables_query_list_current_org_stage;
  "project_variables/query/list_metadata": typeof project_variables_query_list_metadata;
  "project_variables/query/resolve_public_rows": typeof project_variables_query_resolve_public_rows;
  "project_variables/query/resolve_rows": typeof project_variables_query_resolve_rows;
  "project_variables/query/shared": typeof project_variables_query_shared;
  "project_variables/refs": typeof project_variables_refs;
  "project_variables/types": typeof project_variables_types;
  "project_variables/writes/prepare": typeof project_variables_writes_prepare;
  "project_variables/writes/secret": typeof project_variables_writes_secret;
  "project_variables/writes/variants": typeof project_variables_writes_variants;
  projects: typeof projects;
  "projects/create": typeof projects_create;
  "projects/delete": typeof projects_delete;
  "projects/queries": typeof projects_queries;
  "projects/slug": typeof projects_slug;
  "projects/types": typeof projects_types;
  typegen: typeof typegen;
  user_preferences: typeof user_preferences;
  users: typeof users;
  "users/ensure": typeof users_ensure;
  "users/queries": typeof users_queries;
  "users/shared": typeof users_shared;
}>;

/**
 * A utility for referencing Convex functions in your app's public API.
 *
 * Usage:
 * ```js
 * const myFunctionReference = api.myModule.myFunction;
 * ```
 */
export declare const api: FilterApi<
  typeof fullApi,
  FunctionReference<any, "public">
>;

/**
 * A utility for referencing Convex functions in your app's internal API.
 *
 * Usage:
 * ```js
 * const myFunctionReference = internal.myModule.myFunction;
 * ```
 */
export declare const internal: FilterApi<
  typeof fullApi,
  FunctionReference<any, "internal">
>;

export declare const components: {
  autumn: {};
};
