allowBuilds:
  core-js: true
  esbuild: true
  msgpackr-extract: true
minimumReleaseAgeExclude:
  - "@vitest/expect@4.1.10"
  - "@vitest/mocker@4.1.10"
  - "@vitest/pretty-format@4.1.10"
  - "@vitest/runner@4.1.10"
  - "@vitest/snapshot@4.1.10"
  - "@vitest/spy@4.1.10"
  - "@vitest/utils@4.1.10"
  - svelte-auto-href@1.0.1
  - svelte-global-typescript@1.0.1
  - svelte-plugin-composer@1.0.1
  - svelte-sv-extension@1.0.1
  - vitest@4.1.10
  - cuelume@0.1.0
  - svelte-effect-runtime-grammars@4.0.0
  - svelte-effect-runtime@4.0.0
