import { v } from "convex/values";

import { action } from "../confect";
import {
  changePlanForCurrentOrgHandler,
  openBillingPortalForCurrentOrgHandler,
  revokeCurrentUserFreePlanCreditHandler,
  revokeFreePlanCreditForCurrentOrgHandler,
} from "../lib/payments_management";

/**
 * Changes the billing plan for the current authenticated organization.
 *
 * @param ctx The Convex action context.
 * @param args The requested target plan details and expected organization slug.
 * @returns The checkout or applied-plan result for the plan change.
 * @remarks This boundary delegates to the billing management handler and may trigger checkout or audit writes.
 * @lastModified 2026-03-17
 * @author GPT-5.4
 */
export const changePlanForCurrentOrg = action({
  args: {
    expectedOrgSlug: v.string(),
    tier: v.union(v.literal("free"), v.literal("pro"), v.literal("max")),
    interval: v.union(v.literal("monthly"), v.literal("annually")),
    overageMode: v.union(v.literal("without_overages"), v.literal("with_overages")),
    successUrl: v.union(v.string(), v.null()),
  },
  returns: v.object({
    attachedProductId: v.string(),
    checkoutRequired: v.boolean(),
    checkoutUrl: v.union(v.string(), v.null()),
    changeOutcome: v.union(v.literal("applied"), v.literal("scheduled"), v.literal("submitted")),
    effectiveProductId: v.union(v.string(), v.null()),
  }),
  handler: changePlanForCurrentOrgHandler,
});

/**
 * Revokes the free-plan credit currently assigned to the active organization.
 *
 * @param ctx The Convex action context.
 * @param args The expected organization slug.
 * @returns Whether a free-plan credit was revoked.
 * @remarks This boundary delegates to the billing management handler and may update audit and billing snapshot rows.
 * @lastModified 2026-03-17
 * @author GPT-5.4
 */
export const revokeFreePlanCreditForCurrentOrg = action({
  args: {
    expectedOrgSlug: v.string(),
  },
  returns: v.object({
    revoked: v.boolean(),
  }),
  handler: revokeFreePlanCreditForCurrentOrgHandler,
});

/**
 * Revokes the current user's free-plan credit assignment, optionally checking an expected organization id.
 *
 * @param ctx The Convex action context.
 * @param args The expected assigned org id and optional revoke reason.
 * @returns The revoke outcome along with the previous org assignment details.
 * @remarks This boundary delegates to the billing management handler and may update billing snapshot and audit rows.
 * @lastModified 2026-03-17
 * @author GPT-5.4
 */
export const revokeCurrentUserFreePlanCredit = action({
  args: {
    expectedAssignedOrgId: v.union(v.string(), v.null()),
    reason: v.union(v.string(), v.null()),
  },
  returns: v.object({
    revoked: v.boolean(),
    reason: v.union(v.literal("revoked"), v.literal("already_available"), v.literal("mismatch")),
    previousAssignedOrgId: v.union(v.string(), v.null()),
    previousAssignedOrgSlug: v.union(v.string(), v.null()),
  }),
  handler: revokeCurrentUserFreePlanCreditHandler,
});

/**
 * Opens the billing portal for the active organization.
 *
 * @param ctx The Convex action context.
 * @param args The expected organization slug and optional portal return URL.
 * @returns The portal URL generated by Autumn.
 * @remarks This boundary delegates to the billing management handler and emits an audit event when the portal opens.
 * @lastModified 2026-03-17
 * @author GPT-5.4
 */
export const openBillingPortalForCurrentOrg = action({
  args: {
    expectedOrgSlug: v.string(),
    returnUrl: v.union(v.string(), v.null()),
  },
  returns: v.object({
    portalUrl: v.string(),
  }),
  handler: openBillingPortalForCurrentOrgHandler,
});
